// Auto-generated by git hook - DO NOT EDIT
class BuildInfo {
  // Core build info
  static const String version = '1.0.0';
  static const String buildDate = '2025-02-11 15:35:42';
  
  // Git info
  static const String commitHash = 'db499f8';
  static const String branch = 'feat/gantt-filtering-and-sorting';
  static const String lastTag = 'no tag';
  
  // Author of last commit
  static const String lastCommitAuthor = 'renata-sisilio';
  static const String lastCommitEmail = 'renata@seren-ai.co';
  
  // Recent commits (last 5)
  static const List<Map<String, String>> recentCommits = [
    {
      "hash": "db499f8",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "feat(home): quick adding tasks and notes from home page",
      "date": "2025-02-11",
      "relativeDate": "5 hours ago"
    },
    {
      "hash": "1fff87f",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "feat(tasks): create phase page",
      "date": "2025-02-11",
      "relativeDate": "6 hours ago"
    },
    {
      "hash": "23f0860",
      "author": "kc",
      "email": "kylcheng@gmail.com", 
      "message": "chore(task): create task action now assigns project",
      "date": "2025-02-10",
      "relativeDate": "24 hours ago"
    },
    {
      "hash": "04dafee",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "fix(workflow): integrate with current pre-commit hook",
      "date": "2025-02-07",
      "relativeDate": "4 days ago"
    },
    {
      "hash": "9798fe2",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "feat(gantt): show gantt chart at project overview page (web only)",
      "date": "2025-02-05",
      "relativeDate": "6 days ago"
    },
  ];

  // Stats
  static const String totalCommits = '318';
  static const String contributors = '0';
}
