// Auto-generated by git hook - DO NOT EDIT
class BuildInfo {
  // Core build info
  static const String version = '1.0.0';
  static const String buildDate = '2025-04-03 18:11:12';
  
  // Git info
  static const String commitHash = 'b4fc1ab';
  static const String branch = 'main';
  static const String lastTag = 'no tag';
  
  // Author of last commit
  static const String lastCommitAuthor = 'Kyle';
  static const String lastCommitEmail = 'kylcheng@gmail.com';
  
  // Recent commits (last 5)
  static const List<Map<String, String>> recentCommits = [
    {
      "hash": "b4fc1ab",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore: update readme",
      "date": "2025-04-03",
      "relativeDate": "60 minutes ago"
    },
    {
      "hash": "13b054f",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore(ai): fix ai views for notes / modal in web and mobile",
      "date": "2025-04-03",
      "relativeDate": "70 minutes ago"
    },
    {
      "hash": "c18ca78",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore: update readme",
      "date": "2025-04-03",
      "relativeDate": "7 hours ago"
    },
    {
      "hash": "205c9e1",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore(ai): fix chat message view card debug mode spacing",
      "date": "2025-04-03",
      "relativeDate": "8 hours ago"
    },
    {
      "hash": "2b3434a",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "fix: note selection provider issues + support unassigned task tool search",
      "date": "2025-04-02",
      "relativeDate": "25 hours ago"
    },
  ];

  // Stats
  static const String totalCommits = '507';
  static const String contributors = '       0';
}
