// Auto-generated by git hook - DO NOT EDIT
class BuildInfo {
  // Core build info
  static const String version = '1.0.0';
  static const String buildDate = '2025-03-17 11:20:31';
  
  // Git info
  static const String commitHash = '0cae535';
  static const String branch = 'feat/add-days-field-to-task-duration';
  static const String lastTag = 'no tag';
  
  // Author of last commit
  static const String lastCommitAuthor = 'renata-sisilio';
  static const String lastCommitEmail = 'renata@seren-ai.co';
  
  // Recent commits (last 5)
  static const List<Map<String, String>> recentCommits = [
    {
      "hash": "0cae535",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "feat(tasks): update parent task dates based on child task due and start dates",
      "date": "2025-03-17",
      "relativeDate": "16 minutes ago"
    },
    {
      "hash": "18cb9d7",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "fix(tasks): set task estimated duration in days and hours",
      "date": "2025-03-17",
      "relativeDate": "16 minutes ago"
    },
    {
      "hash": "c780c01",
      "author": "renata-sisilio",
      "email": "renata@seren-ai.co", 
      "message": "feat(orgs): allow users to delete (disable) orgs (#183)",
      "date": "2025-03-17",
      "relativeDate": "28 minutes ago"
    },
    {
      "hash": "bc508f1",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore: pr comments",
      "date": "2025-03-17",
      "relativeDate": "2 hours ago"
    },
    {
      "hash": "2a1e617",
      "author": "Kyle",
      "email": "kylcheng@gmail.com", 
      "message": "chore(tasks): refactor task list views",
      "date": "2025-03-16",
      "relativeDate": "17 hours ago"
    },
  ];

  // Stats
  static const String totalCommits = '426';
  static const String contributors = '0';
}
