name: seren_ai_flutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1

  # For styles 
  flex_color_scheme: ^7.3.1

  # Supabase
  supabase_flutter: ^2.0.0
  supabase_auth_ui: ^0.5.0

  intl: ^0.19.0

  # Deep links 
  app_links: ^6.1.1

  shared_preferences: ^2.2.3
  logging: ^1.2.0

  # useState hooks 
  flutter_hooks: ^0.20.5
  # hooks and riverpod 
  hooks_riverpod: ^2.5.1

  json_annotation: ^4.9.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # for running: 
  # flutter pub run build_runner build
  build_runner: ^2.4.11

  # code generation of to/from json code 
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  