// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSdZyPukT6E-NF-L8MkZMCZL2SS-s7zU',
    appId: '1:888730365208:android:83325c231177b43b09c26d',
    messagingSenderId: '888730365208',
    projectId: 'seren-ai',
    storageBucket: 'seren-ai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZhXWbRlQN1d2ySgk1XLTyUDc0qToMr8',
    appId: '1:888730365208:web:a43dd784069dd21009c26d',
    messagingSenderId: '888730365208',
    projectId: 'seren-ai',
    authDomain: 'seren-ai.firebaseapp.com',
    storageBucket: 'seren-ai.firebasestorage.app',
    measurementId: 'G-5D5MPDTD3N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sVLwh5rvXDwk8H6MeZp9AqhSCdJRlco',
    appId: '1:888730365208:ios:bab4adc3c9e59f4309c26d',
    messagingSenderId: '888730365208',
    projectId: 'seren-ai',
    storageBucket: 'seren-ai.firebasestorage.app',
    iosBundleId: 'com.serentech.serenai-ios',
  );

}