import 'dart:convert';
import 'package:seren_ai_flutter/services/data/ai_chats/models/ai_chat_message_model.dart';

/// Sample tool messages for testing different request types
/// These should be generated by the ai, we just hardcode these formats here for testing
final sampleClockInRequest = AiChatMessageModel(
  type: AiChatMessageType.tool,
  content: jsonEncode([{
    'request_type': 'action_request',
    'action_request_type': 'clock_in',
    //'args': {'reason': 'Starting work day'}
  }]),
  parentChatThreadId: 'test-thread-1'
);

final sampleClockOutRequest = AiChatMessageModel(
  type: AiChatMessageType.tool,
  content: jsonEncode([{
    'request_type': 'action_request', 
    'action_request_type': 'clock_out',
    //'args': {'reason': 'Ending work day'}
  }]),
  parentChatThreadId: 'test-thread-1'
);

final sampleCurrentShiftInfoRequest = AiChatMessageModel(
  type: AiChatMessageType.tool,
  content: jsonEncode([{
    'request_type': 'info_request',
    'info_request_type': 'current_shift',
    'show_only': true,
    //'args': {'detail_level': 'full'}
  }]),
  parentChatThreadId: 'test-thread-1'
);

final sampleShiftHistoryRequest = AiChatMessageModel(
  type: AiChatMessageType.tool,
  content: jsonEncode([{
    'request_type': 'info_request',
    'info_request_type': 'shift_history',
    'show_only': true,
    //'args': {'days': '7'}
  }]),
  parentChatThreadId: 'test-thread-1'
);

final sampleShiftsPageRequest = AiChatMessageModel(
  type: AiChatMessageType.tool,
  content: jsonEncode([{
    'request_type': 'ui_action',
    'ui_action_request_type': 'shifts_page',
    //'args': {'view': 'calendar'}
  }]),
  parentChatThreadId: 'test-thread-1'
);

// List containing all sample requests for easy access
final List<AiChatMessageModel> allSampleRequests = [
  sampleClockInRequest,
  sampleClockOutRequest, 
  sampleCurrentShiftInfoRequest,
  sampleShiftHistoryRequest,
  sampleShiftsPageRequest
];
