name: Android Release AAB

on:
  push:
    branches:
      - main  # Only run when changes are pushed to main
  workflow_dispatch:  # Allows manual triggers from GitHub UI
    inputs:
      build_mode:
        description: 'Build mode (release/debug)'
        required: true
        default: 'release'
        type: choice
        options:
          - release

env:
  JAVA_VERSION: '17'
  FLUTTER_BUILD_MODE: release
  FLUTTER_VERSION_NAME: 1.0.0
  FLUTTER_VERSION_CODE: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter 3.24.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Update Gradle files
        run: |
          cat << 'EOF' >> android/app/build.gradle

          android {
            buildTypes {
                release {
                    signingConfig null
                    minifyEnabled true
                    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                }
            }
          }
          EOF

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Debug - List build directory
        run: |
          echo "Listing bundle directory contents:"
          ls -R build/app/outputs/bundle/release/

      - name: Sign App Bundle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Copy the keystore file
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/my-release-key.jks
          
          # Sign the App Bundle
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore android/app/my-release-key.jks \
            -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD \
            build/app/outputs/bundle/release/app-release-unsigned.aab $KEY_ALIAS

          # Move the signed bundle to a new name
          mv build/app/outputs/bundle/release/app-release-unsigned.aab build/app/outputs/bundle/release/app-release-signed.aab

          # Verify App Bundle
          jarsigner -verify build/app/outputs/bundle/release/app-release-signed.aab

      - name: Upload App Bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release-signed.aab
